### ISSUE TITLE
Volumes analysis

### ISSUE THREAD

**Issue by potterhead-rahul** [razorpay/business_analytics#1]
### Briefly describe the objective of data analysis request.

Volumes analysis of different merchants

### Team

Mark an (X) before your team?

- [ X ] Sales
- [ ] Marketing
- [ ] Finance
- [ ] CSM
- [ ] Product
- [ ] Operations
  - [ ] Onboarding
  - [ ] Support
  - [ ] Others
- [ ] HR

### What is the priority level for this data request?

- [ ] Low
- [ ] Medium
- [X ] High

### Mark an (X) before the type of requirement?

- [ ] Client
- [X ] Internal

**Mention the exact fields/metrics required in the data?

Ans: Merchant_id , Name , Volumes

**What is the time period window you want to consider for the analysis?

Ans: 1 year

### Is this data requirement recurring?

- [ X ] Yes
- [ ] No

**If data requirement is recurring,mention the time intervals after which data is required.

Ans: Every 7 days

**Any other details you would like to share?

Ans: Nopes

**Comment by Prerit22** [comment]
What is the level at which data is required?
