### ISSUE TITLE
Freshtohome Late Auth data for Oct

### ISSUE THREAD

**Issue by shikhagulati** [razorpay/business_analytics#6]
### Briefly describe the objective of data analysis request.
Late auth data for freshtohome for october to understand what percentage of transactions are late auth cases

### Team

Mark an (X) before your team?

- [ ] Sales
- [ ] Marketing
- [ ] Finance
- [X] CSM 
- [ ] Product
- [ ] Operations
  - [ ] Onboarding
  - [ ] Support
  - [ ] Others
- [ ] HR

### What is the priority level for this data request?

- [ ] Low
- [ ] Medium
- [X] High 

### Mark an (X) before the type of requirement?

- [X] Client 
- [ ] Internal

**Mention the exact fields/metrics required in the data?

Ans: 

**What is the time period window you want to consider for the analysis?

Ans: 

### Is this data requirement recurring?

- [ ] Yes
- [ ] No

**If data requirement is recurring,mention the time intervals after which data is required.

Ans: 

**Any other details you would like to share?

Ans:

**Comment by Prerit22** [comment]
@shikhagulati : The late auth percentage is only 0.56% on authorized txns for the month of october. Have shared the data with you on slack. Can you please close this issue.
